name: 'earth_monitoring'
version: '1.0.0'
config-version: 2

profile: 'earth_monitoring'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  earth_monitoring:
    staging:
      +materialized: view
    mart:
      +materialized: table
