earth_monitoring:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: postgres
      password: postgres
      port: 5432
      dbname: earth_monitoring
      schema: public
      threads: 4