services:
  postgres:
    image: postgres:13
    platform: linux/amd64
    container_name: earth_monitoring_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=earth_monitoring
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      postgres -c "max_connections=100"

  airflow-webserver:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    platform: linux/amd64
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - OPENAQ_API_KEY=${OPENAQ_API_KEY}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres:5432/earth_monitoring
      - AIRFLOW_CONN_POSTGRES_DEFAULT=postgresql+psycopg2://postgres:postgres@postgres:5432/earth_monitoring
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/config:/opt/airflow/config
      # - ./data_collection:/opt/airflow/data_collection
      - ./dbt:/opt/airflow/dbt
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    platform: linux/amd64
    depends_on:
      - airflow-webserver
    environment:
      - OPENAQ_API_KEY=${OPENAQ_API_KEY}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres:5432/earth_monitoring
      - AIRFLOW_CONN_POSTGRES_DEFAULT=postgresql+psycopg2://postgres:postgres@postgres:5432/earth_monitoring
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/config:/opt/airflow/config
      # - ./data_collection:/opt/airflow/data_collection
      - ./dbt:/opt/airflow/dbt
    command: scheduler
  # data-collector:
  #   build:
  #     context: ./data_collection
  #     dockerfile: Dockerfile
  #   platform: linux/amd64
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   volumes:
  #     - ./data_collection:/app
  #   env_file:
  #     - ./data_collection/.env


volumes:
  postgres_data:
